version: '3'

services:
  botty_mcbotface:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=latest
    image: python:3.12-slim
    container_name: botty_mcbotface
    user: '1200'
    env_file:
      - .env
    working_dir: /app
    restart: unless-stopped
    labels:
      - authors="Discobrick"
      - org.opencontainers.image.ref.name=ubuntu
      - org.opencontainers.image.version=20.04
    command: "/usr/bin/python3 bot.py &"
    runtime: runc

