version: '3'

services:
  botty_mcbotface:
    build:
      context: .
      dockerfile: Dockerfile
    image: botty_mcbotface:latest
    container_name: botty_mcbotface
    user: "1200:1200"
    env_file:
      - .env
    working_dir: /app
    restart: unless-stopped
    labels:
      - authors="Discobrick"
      - org.opencontainers.image.ref.name=botty_mcbotface
      - org.opencontainers.image.version=latest
    runtime: runc
    volumes:
      - ./data:/app/data