
services:
  botty_mcbotface:
    build:
      context: .
      dockerfile: Dockerfile
    image: botty_mcbotface:latest
    container_name: botty_mcbotface
    user: "1200:1200"
    env_file:
      - .env
    working_dir: /app
    restart: always
    labels:
      - authors="Discobrick"
      - org.opencontainers.image.ref.name=botty_mcbotface
      - org.opencontainers.image.version=latest
    runtime: runc
    environment:
      - PREFERENCES_FILE=/data/preferences.json
      - ERROR_LOG_FILE=/data/error.log
      - FAILED_LINKS_LOG_FILE=/data/failed_links.log
      - MAX_WORKERS=10
    volumes:
      - bot-data:/data
      # Using a named volume for all persistent data instead of binding to host files

volumes:
  bot-data:
